variables:
  # Gitlab namespace with branch name: "namespace-branchname"
  # NAMESPACE: ${CI_PROJECT_NAMESPACE}-${CI_COMMIT_REF_SLUG}
  NAMESPACE: better-website
  DOCKER_IMAGE_URL: asksven/better-website

stages:
  - generate
  - build
  - test_deploy
  - test_status
  - test_run
  - test_clean
  - deploy
  - deploy_test
  - status
  - cleanup

# ===========================================
#  Generate the static website
# ===========================================
generate hugo:
  before_script:
  - git submodule sync --recursive
  - git submodule update --init --recursive
  stage: generate
  image: jojomi/hugo:0.53
  tags:
  - asksven-homelab-prd-public
  script:
  # baseURL = "/" is required as we want to build the docker image once and deploy it to multiple domains (e.g. for testing)  
  - mkdir public && cd src && hugo --baseURL "/" --cleanDestinationDir --destination ../public/
  artifacts:
    paths:
    - public

# generate hugo:
#   stage: generate
#   image: jojomi/hugo:0.44
#   tags:
#   - asksven-homelab-dev  
#   script:
#   - mkdir public && cd src && hugo --cleanDestinationDir --destination ../public/
#   artifacts:
#     paths:
#     - public


# build container with img priv:
#   stage: build
#   image: r.j3ss.co/img
#   tags:
#     - asksven-homelab-dev
#   script:
#     - echo "$DOCKER_REGISTRY_PASSWORD2" | img login -u "$DOCKER_REGISTRY_USER2" --password-stdin ${DOCKER_REGISTRY2}
#     - img pull ${DOCKER_REGISTRY2}/${DOCKER_IMAGE_URL2}:${CI_BUILD_REF_SLUG} || true
#     - img build -t ${DOCKER_REGISTRY2}/${DOCKER_IMAGE_URL2}:${CI_BUILD_REF} .
#     - echo pushing ${DOCKER_REGISTRY2}/${DOCKER_IMAGE_URL2}:${CI_BUILD_REF} 
#     - img push ${DOCKER_REGISTRY2}/${DOCKER_IMAGE_URL2}:${CI_BUILD_REF}
#     - img tag ${DOCKER_REGISTRY2}/${DOCKER_IMAGE_URL2}:${CI_BUILD_REF} ${DOCKER_REGISTRY2}/${DOCKER_IMAGE_URL2}:${CI_BUILD_REF_SLUG}
#     - echo pushing ${DOCKER_REGISTRY2}/${DOCKER_IMAGE_URL2}:${CI_BUILD_REF_SLUG} 
#     - img push ${DOCKER_REGISTRY2}/${DOCKER_IMAGE_URL2}:${CI_BUILD_REF_SLUG}
lint_dockerfile:
  stage: build
  tags:
    - asksven-homelab-prd-public
  image: hadolint/hadolint:latest-debian
  script:
    - hadolint Dockerfile

build container:
  stage: build
  image: docker:18.06.1-ce
  tags:
    - asksven-homelab-prd-public
  services:
    - docker:18.06.1-ce-dind
  variables:
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_DRIVER: overlay2
  script:
    - docker login -u "${DOCKER_REGISTRY_USER}" -p "$DOCKER_REGISTRY_PASSWORD" ${DOCKER_REGISTRY}
    - docker pull ${DOCKER_REGISTRY}/${DOCKER_IMAGE_URL}:${CI_BUILD_REF_SLUG} || true
    - docker build --cache-from ${DOCKER_REGISTRY}/${DOCKER_IMAGE_URL}:${CI_BUILD_REF_SLUG} -t ${DOCKER_REGISTRY}/${DOCKER_IMAGE_URL}:${CI_BUILD_REF} .
    - echo pushing ${DOCKER_REGISTRY}/${DOCKER_IMAGE_URL}:${CI_BUILD_REF} 
    - docker push ${DOCKER_REGISTRY}/${DOCKER_IMAGE_URL}:${CI_BUILD_REF}
    - docker tag ${DOCKER_REGISTRY}/${DOCKER_IMAGE_URL}:${CI_BUILD_REF} ${DOCKER_REGISTRY}/${DOCKER_IMAGE_URL}:${CI_BUILD_REF_SLUG}
    - echo pushing ${DOCKER_REGISTRY}/${DOCKER_IMAGE_URL}:${CI_BUILD_REF_SLUG} 
    - docker push ${DOCKER_REGISTRY}/${DOCKER_IMAGE_URL}:${CI_BUILD_REF_SLUG}

# ===========================================
#  Templates
# ===========================================
.deploy_template: &deploy_template
  image: codemelter/docker-kubernetes-deploy
  script:
  - cd ops && ./deploy.sh
  artifacts:
    paths:
    - ops

.test_template: &test_template
  image: joyzoursky/python-chromedriver:3.6
  before_script:
    - pip install -r tests/webtests_1/requirements.txt
  tags:
    - asksven-homelab-prd-public
  script:
    - cd tests/webtests_1
    - python -u selenium-python.py
  artifacts:
    paths:
    - tests/output

.cleanup_template: &cleanup_template
  image: codemelter/docker-kubernetes-deploy
  script:
  - echo We are going to delete namespace $NAMESPACE
  - kubectl delete ns ${NAMESPACE}

.status_template: &status_template
  image: codemelter/docker-kubernetes-deploy
  script:
  - kubectl describe pods,deployment,ing --namespace=${NAMESPACE}

# ===========================================
#  Test stage:
#    1. deploy to a unique URL in an own ns
#    2. run ui tests
#    3. tear down
# ===========================================
deploy temp:
  stage: test_deploy
  <<: *deploy_template
  tags:
    - asksven-homelab-prd-public
  variables:
    DEPLOY_ENV: temp
    # we need a temp name to deploy to
    NAMESPACE: ${CI_PROJECT_NAME}-${CI_BUILD_REF}

status temp_deployment:
  stage: test_status
  <<: *status_template
  tags:
    - asksven-homelab-prd-public
  variables:
    DEPLOY_ENV: temp
    # we deployed to a temp name
    NAMESPACE: ${CI_PROJECT_NAME}-${CI_BUILD_REF}

ui test temp deployment:
  stage: test_run
  <<: *test_template
  tags:
    - asksven-homelab-prd-public
  variables:
    DEPLOY_ENV: temp
    # we deployed to a temp name
    NAMESPACE: ${CI_PROJECT_NAME}-${CI_BUILD_REF}
    # we need to pass the URL to test
    BASE_URL: https://better-${CI_BUILD_REF}.asksven.io

cleanup temp deployment:
  stage: test_clean
  <<: *cleanup_template
  tags:
    - asksven-homelab-prd-public
  variables:
    DEPLOY_ENV: temp
    # we deployed to a temp name
    NAMESPACE: ${CI_PROJECT_NAME}-${CI_BUILD_REF}

# ===========================================
#  Deployment stage, either:
#    a) deploy for branch
#   or
#    b) deploy to prd
# ===========================================
deploy for branch:
  stage: deploy
  <<: *deploy_template
  tags:
    - asksven-homelab-prd-public
  variables:
    DEPLOY_ENV: testing
  except:
  - master

ui test branch deployment:
  stage: deploy_test
  <<: *test_template
  tags:
    - asksven-homelab-prd-public
  variables:
    DEPLOY_ENV: testing
    # we need to pass the URL to test
    BASE_URL: https://better-${CI_BUILD_REF_SLUG}.asksven.io
  except:
  - master

deploy for prd:
  stage: deploy
  <<: *deploy_template
  tags:
    - asksven-homelab-prd-public
  variables:
    DEPLOY_ENV: production
  only:
  - master

deploy for dr:
  stage: deploy
  <<: *deploy_template
  tags:
    - asksven-homelab-prd-public-new
  variables:
    DEPLOY_ENV: dr
  only:
  - master
  except:
    - schedule

ui test prd deployment:
  stage: deploy_test
  <<: *test_template
  tags:
    - asksven-homelab-prd-public
  variables:
    DEPLOY_ENV: production
    # we need to pass the URL to test
    BASE_URL: https://better.asksven.io
  only:
  - master

# ===========================================
#  Show final status
#    a) deploy for branch
#   or
#    b) deploy to prd
# ===========================================
status namespace:
  stage: status
  <<: *status_template
  tags:
    - asksven-homelab-prd-public


