variables:
  # Gitlab namespace with branch name: "namespace-branchname"
  # NAMESPACE: ${CI_PROJECT_NAMESPACE}-${CI_COMMIT_REF_SLUG}
  NAMESPACE: better-website

stages:
  - generate
#  - build
#  - deploy
#  - status
#  - cleanup

generate hugo:
  stage: generate
  image: jojomi/hugo:0.44
  script:
  - mkdir public && cd src && hugo --cleanDestinationDir --destination ../public/
   artifacts:
     paths:
     - public

# .deploy_template: &deploy_template
#   stage: deploy
#   image: ksiebel/docker-kubernetes-deploy
#   script:
#   - cd ops && ./deploy.sh
#   artifacts:
#     paths:
#     - ops

# .deploy_template_azure: &deploy_template_azure
#   <<: *deploy_template
#   tags:
#   - monitoring-poc-cluster
#   variables:
#     DEPLOY_ENV: azure
#   only:
#   - master@asksven/prometheus-deployment

# .deploy_template_dev: &deploy_template_dev
#   <<: *deploy_template
#   variables:
#     DEPLOY_ENV: development
#   only:
#   - master@sven.knispel/prometheus-deployment-dev


# # stable to production:
# #   <<: *deploy_template_production

# # stable to staging:
# #   <<: *deploy_template_staging

# stable to dev:
#   <<: *deploy_template_dev


# .status_template: &status_template
#   stage: status
#   image: ksiebel/docker-kubernetes-deploy
#   script:
#   - kubectl describe pods,svc,deployment,ing --namespace=${NAMESPACE}

# status namespace dev:
#   <<: *status_template
#   only:
#   - master


# .cleanup_template: &cleanup_template
#   stage: status
#   image: ksiebel/docker-kubernetes-deploy
#   script:
#   - kubectl delete ${NAMESPACE}
#   when: manual

# cleanup dev:
#   <<: *cleanup_template
#   only:
#   - master
  