apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: project-better
spec:
  replicas: 2
  template:
    metadata:
      name: project-better-web
      labels:
        app: project-better-app
        role: frontend
    spec:
      containers:
      - name: project-better
        image: quay.io/asksven/better-website:{{ TAG }}
        imagePullPolicy: Always
        ports:
        - name: frontend
          containerPort: 80
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: project-better-svc
spec:
  selector:
    app: project-better-app
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: project-better
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: {{ HOST1 }}
    http:
      paths:
      - backend:
          serviceName: project-better-svc
          servicePort: 80
        path: /  
